development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.db
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  database: railwayapp_production
  username: railwayapp
  password: <%= ENV["RAILWAYAPP_DATABASE_PASSWORD"] %>
  pool: 5
